### ISSUE TITLE
Visualization of Latent ODE Reconstruction Trajectories

### ISSUE THREAD

**Issue by jzhao9921** [itmoon7/survlatent_ode#1]
Hi itmoon7! I feel very honored to learn such great code, but I encountered a small problem when reproducing the code, related to the visualization of Latent ODE reconstruction trajectories. Due to my limited knowledge of coding, I cannot modify the code in the laten_ode.py file to make the get_reconstruction_traj and _plot_recons_traj functions run. Because DecoderBlock function does not exist in latent_ode.py.Could you tell me how to modify the code in the notebook_example.py file so that the final results include images that plot the observed trajectory, predicted trajectory, and extrapolation trajectory for each feature? Thank you for your help and have a pleasant day!

**Comment by itmoon7** [comment]
Hello jzhao9921, thank you for getting in touch. We are currently developing an extension for SurvLatent ODE, aiming to better model continuous streams of data. This extension will also include the functionality you've requested, like the visualization of extrapolated trajectories for each feature. Please keep an eye on this repo for updates, and we'll inform you as soon as it becomes available!
